### ISSUE TITLE
Problem with an item

### ISSUE THREAD

**Issue by kotenok2000** [ArchiveTeam/urls-grab#11]
Item listed below constantly redownloads common file for each page
[новый 1.txt](https://github.com/ArchiveTeam/urls-grab/files/8096535/1.txt)

"Item https://lh6.googleusercontent.com/45Y6LKltYhQ7nRZE83hIm0GcMKvMj4ztz9WQSCu07nLwttRXcXHoUPDMpFhXVdjWpTnmAw=w16383https://redditsave.com/info?url=/r/dankinindia/comments/sv89xd/https://zbmath.org/pdf/0058.09001.pdfhttps://i0.wp.com/prtimes.jp/i/77656/69/resize/d77656-69-e720c0a5ae3af8b37f30-4.jpg&s3=77656-69-6563d02322b6ab5a68db1458c2e53eff-3900x554.jpg?resize=1360%2C193&ssl=1https://mb-training.de/wp-content/themes/twentynineteen/js/priority-menu.js?ver=20181214https://wn.nr/fpyLMHhttps://ilsaronno.it/wp-content/uploads/2022/02/20220218-ramo-caduto-parco-alpini-1-100x75.jpghttp://www.bswwbj.com/uploads/images/1873401.jpgcustom:random=202202&url=https%3a%2f%2flp%2eyunth%2ejp%2fhttps://voshod-news.ru/voshodimages/0/190/u-rossijskogo-mida-obrushilsya-sajt-posle-publikatsii-pisma-k-ssha.jpghttps://content1a.omroep.nl/urishieldv2/l27m276c96b06212606500620caace000000.64ee3c30fc50107922294d2ea393b3d8/ntr/diversiteit/caribischnetwerk/audio/guerakorsou.mp3https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/695f5937-4efb-40b4-9632-62f559f0ceba/ddf8dgm-bd5f25ed-64e0-4039-9eee-e4e5ad554c5a.png/v1/crop/w_286,h_350,x_0,y_0,scl_0.4484375,strp/another_mugen_ghost_by_jk5201_ddf8dgm-350t.pnghttp://img.koreatimes.com/2015/js/login_popup.js?v=2022-02-178615https://s.yimg.com/fz/api/res/1.2/brDTe13GBE8z_hb6Dj1SJQ--~C/YXBwaWQ9c3JjaGRkO2ZpPWZpbGw7aD0yMjg7cHhvZmY9MDtweW9mZj0wO3E9ODA7dz00MDA-/https://www.bing.com/thcustom:all=1&depth=0&keep_all=0&url=https%3a%2f%2fwww%2egoogle%2ecom%2fsearch%3fq%3dEugene%2bRegister%2bGuard%26hl%3den%26gl%3dus%26authuser%3d0%26tbs%3dar%3a1%26tbm%3dnws%26ei%3dFpYLYtvrO6jFkPIPl4iiwAw%26start%3d80%26sa%3dN%26ved%3d2ahUKEwjbzsDX1IH2AhWoIkQIHReECMgQ8tMDegQIARBGhttps://preview.redd.it/j9x8eqthn8i81.jpghttps://www.resalelot.org/upload/CL/TN/9/CLListing-24359-Photo2.jpg?ts=d9383720-7293-4798-9f5a-c53c80d053fehttps://www.ok.co.uk/lifestyle/foxy-eyes-removing-ribs-adding-26256654https://shenasname.ir/wp-content/cache/wpfc-minified/f4juxosw/e0irl.csshttps://image.rakuten.co.jp/alice-store/cabinet/a070055/imgrc0162697388.jpghttp://feb-web.ru/feb/common/tree.asp?/feb/ushakov/ush-abc/02/us115603.htm&encyc=1&click=no&vtsrch=onhttp://www.pokepara.jp/tokyo/m9/a10034/shop4995/gal/284027/blog/diary_18274552.htmlhttps://bit.ly/3oNGCZwhttp://gf.me/u/2zxfkyhttps://www.vku.edu.kz/sites/default/files/images/photo/.jpghttps://images.groenekring.be/2020-03/2017_beelden_wat_is_groene_kring_1.jpg?auto=format&crop=faces&fit=crop&h=420&ixlib=php-1.1.0&q=75&w=620http://msongbad.com/nha-cai-uy-tin/yug0v.htmlhttps://smart.livehindustan.com/patna/news/viral-video-on-the-internet-bihar-gopalganj-social-media-viral-video-police-line-dance-with-dancer-sdpo-sanjeev-kumar-man-dancing-in-the-video-81645169260467.htmlhttps://antiqueww-wpengine.netdna-ssl.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-style.csshttps://www.aguafrianoticias.com.br/noticia/33929/ce-discutira-criacao-de-fundo-patrimonial-nas-universidades-federaishttps://i0.wp.com/www.gbhbl.com/wp-content/uploads/2022/02/Chellcy-Reitsma-PR-photo.jpg?resize=40%2C40&ssl=1https://turkmenportal.com/images/uploads/cache/autos/9951b567816e3f6cc5744b614e9cbc0e-8805750-72x72-2.jpghttps://georgetownenergypartners.com/?rand=1645091867https://www.dailymaverick.co.za/dm-admin/?redirect_to=https%3A%2F%2Fwww.dailymaverick.co.za%2Farticle%2F2022-02-15-glencore-sets-aside-1-5bn-for-graft-settlements-after-earnings-surge-on-record-commodity-prices%2Fhttp://feb-web.ru/feb/common/tree.asp?/feb/ushakov/ush-abc/11/us1e9202.htm&encyc=1&click=no&vtsrch=onhttps://giv.gg/r/t4sdaQ-WOzafjhttps://espacodemocratico.org.br/wp-content/uploads/2022/02/Poupanca-768x459.jpghttps://i0.wp.com/recognizingpotential.com/wp-content/uploads/2022/02/Connected.png?resize=300%2C300&ssl=1"

**Comment by kotenok2000** [comment]
Now it crashed

**Comment by Arkiver2** [comment]
This should be fixed with https://github.com/ArchiveTeam/urls-grab/blob/master/urls.lua#L342-L346 for this (very) special case.
